### ISSUE TITLE
Thanks for sharing!

### ISSUE THREAD

**Issue by lucavignali** [waylongo/cis-challenge-energy-prediction#1]
Congratulations and thanks for sharing your valuable research results.

I just want to be sure that I understood correctly that the rAE you are mentioning in the paper is the Relative Absolute Error as defined in the competition. I'm asking because the paper is reporting root Absolute Error instead.

Thanks and again Congratulations!

Br,
Luca

**Comment by waylongo** [comment]
Thanks Luca. It's the same score. It might be a mistake in the report.

Waylon

**Comment by waylongo** [comment]
Closed the issue.
